spring:
  application:
    name: nft
  data:
    mongodb:
      uri: mongodb://root:secret@localhost:27017/nftdb
  mail:
    host: smtp.gmail.com
    port: 587
    username: anadisankritya007@gmail.com
    password: ifxzukoxcwloliny
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 8080
  servlet:
    context-path: /nft

logging:
  level:
    org.springframework.security: DEBUG


sms:
  api:
    url: "https://api.textlocal.in/send/"
    key: "yourApiKey"
  sender: "TXTLCL"